# Generated by Django 4.1.7 on 2024-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homs', '0002_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
