# Generated by Django 4.1.7 on 2024-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homs', '0004_patient_tests_alter_question_pub_date_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
