# Generated by Django 4.1.7 on 2024-03-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homs', '0006_author_book_publisher_remove_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
