# Generated by Django 4.1.7 on 2024-03-23 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homs', '0007_remove_book_authors_remove_book_publisher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prise', models.PositiveSmallIntegerField()),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('ref_male', models.TextField(blank=True, max_length=5000)),
                ('ref_female', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.PositiveSmallIntegerField()),
                ('date', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], max_length=5)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('dr', models.CharField(default='-', max_length=30)),
                ('entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homs.test')),
            ],
        ),
    ]
