# Generated by Django 4.1.7 on 2024-03-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homs', '0009_test_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
