# Generated by Django 4.1.7 on 2024-03-23 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homs', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='entry',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
