# Generated by Django 5.0.3 on 2024-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homs", "0014_alter_result_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="id",
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=models.BigAutoField(
                default=123154564,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
