# Generated by Django 5.0.3 on 2024-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homs", "0016_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(
                default=b"\xfd\xd6l~\x95NH*\x1e7o=", max_length=12, unique=True
            ),
        ),
    ]
