# Generated by Django 5.0.3 on 2024-03-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homs", "0017_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="patient",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
