# Generated by Django 5.0.3 on 2024-03-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homs", "0021_alter_patient_patient_id_print"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(
                default="223245177238", editable=False, max_length=12, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="Print",
        ),
    ]
